// frontends/web/src/App.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import type { DockviewApi, DockviewReadyEvent } from 'dockview';
import Dock from './dock/Dock';
import ActivityBar from './shell/ActivityBar';
import SideBar from './shell/SideBar';
import { TooltipProvider } from '@virta/ui-kit';
import type { ViewId } from './shell/views';
import { ThemeProvider } from './theme';

export default function App() {
  const [activeView, setActiveView] = useState<ViewId>('panels');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [theme, setTheme] = useState('graphite-dark');
  const apiRef = useRef<DockviewApi | null>(null);

  // Reflect the chosen theme onto the document so the token theme blocks switch.
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const onReady = useCallback((event: DockviewReadyEvent) => {
    const api = event.api;
    apiRef.current = api;
    if (api.panels.length > 0) return; // idempotent under React StrictMode remounts

    const add = (id: string, kind: string, title: string, position?: Parameters<DockviewApi['addPanel']>[0]['position']) =>
      api.addPanel({ id, component: 'panel', params: { kind }, title, position });

    // Seed a representative workspace: a left group with the feed + mod queue as tabs, and a
    // right column splitting stats over the stream. Proves tabs, split, resize, drag rearrange.
    add('feed', 'feed', 'Unified feed');
    add('mods', 'mods', 'Mod queue', { referencePanel: 'feed', direction: 'within' });
    add('stats', 'stats', 'Stats', { referencePanel: 'feed', direction: 'right' });
    add('stream', 'stream', 'Stream', { referencePanel: 'stats', direction: 'below' });
  }, []);

  const selectView = useCallback(
    (view: ViewId) => {
      // Re-selecting the active view toggles the side bar, matching VS Code's activity bar.
      if (view === activeView) {
        setSidebarOpen((open) => !open);
      } else {
        setActiveView(view);
        setSidebarOpen(true);
      }
    },
    [activeView],
  );

  const openPanel = useCallback((kind: string, title: string) => {
    const api = apiRef.current;
    if (!api) return;
    const existing = api.getPanel(kind);
    if (existing) {
      existing.api.setActive(); // focus an already-open panel instead of duplicating it
      return;
    }
    api.addPanel({ id: kind, component: 'panel', params: { kind }, title });
  }, []);

  // Settings opens as its own dock panel (not a side-bar pane): it needs room for many
  // categories. Re-invoking focuses the existing panel.
  const openSettings = useCallback(() => {
    const api = apiRef.current;
    if (!api) return;
    const existing = api.getPanel('settings');
    if (existing) {
      existing.api.setActive();
      return;
    }
    api.addPanel({ id: 'settings', component: 'settings', title: 'Settings' });
  }, []);

  return (
    <ThemeProvider value={{ theme, setTheme }}>
      <TooltipProvider>
        <div className="shell">
          <ActivityBar activeView={activeView} sidebarOpen={sidebarOpen} onSelect={selectView} onOpenSettings={openSettings} />
          {sidebarOpen && <SideBar view={activeView} openPanel={openPanel} />}
          <div className="dock-host">
            <Dock onReady={onReady} />
          </div>
        </div>
      </TooltipProvider>
    </ThemeProvider>
  );
}

// frontends/web/src/App.svelte
<script lang="ts">
  import { mount, unmount } from 'svelte';
  import { createDock, type Dock } from './dock/dock';
  import Panel from './panels/Panel.svelte';
  import ActivityBar from './shell/ActivityBar.svelte';
  import SideBar from './shell/SideBar.svelte';
  import type { ViewId } from './shell/views';

  let activeView = $state<ViewId>('panels');
  let sidebarOpen = $state(true);
  let theme = $state('graphite-dark');
  let dock: Dock | undefined;

  // Reflect the chosen theme onto the document so the token theme blocks switch.
  $effect(() => {
    document.documentElement.dataset.theme = theme;
  });

  // Svelte action: own the dock host element's lifecycle, seeding the initial layout once.
  function dockHost(node: HTMLElement) {
    const d = createDock(node, {
      render(el, kind) {
        const cmp = mount(Panel, { target: el, props: { kind } });
        return () => void unmount(cmp);
      },
    });
    d.add({ id: 'feed', kind: 'feed', title: 'Unified feed' });
    d.add({ id: 'mods', kind: 'mods', title: 'Mod queue', position: { referencePanelId: 'feed', direction: 'within' } });
    d.add({ id: 'stats', kind: 'stats', title: 'Stats', position: { referencePanelId: 'feed', direction: 'right' } });
    d.add({ id: 'stream', kind: 'stream', title: 'Stream', position: { referencePanelId: 'stats', direction: 'below' } });
    dock = d;
    return {
      destroy() {
        d.dispose();
        dock = undefined;
      },
    };
  }

  function selectView(view: ViewId) {
    // Re-selecting the active view toggles the side bar, matching VS Code's activity bar.
    if (view === activeView) {
      sidebarOpen = !sidebarOpen;
    } else {
      activeView = view;
      sidebarOpen = true;
    }
  }

  function openPanel(kind: string, title: string) {
    dock?.open({ id: kind, kind, title });
  }
</script>

<div class="shell">
  <ActivityBar {activeView} {sidebarOpen} onselect={selectView} />
  {#if sidebarOpen}
    <SideBar view={activeView} {theme} {openPanel} setTheme={(t) => (theme = t)} />
  {/if}
  <div class="dock-host" use:dockHost></div>
</div>

<style>
  .shell {
    display: flex;
    height: 100%;
    min-height: 0;
  }
  .dock-host {
    flex: 1 1 auto;
    min-width: 0;
    height: 100%;
  }
</style>
